name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  # Next.js Website Tests
  website-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run ESLint
      run: npm run lint
    
    - name: Build Next.js
      run: npm run build
    
    - name: Run tests
      run: npm test --if-present

  # VS Code Extension Tests
  extension-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: extension/package-lock.json
    
    - name: Install extension dependencies
      run: |
        cd extension
        npm ci
    
    - name: Compile extension
      run: |
        cd extension
        npm run compile
    
    - name: Run extension tests
      run: |
        cd extension
        xvfb-run -a npm test --if-present

  # Deploy to Vercel (Website)
  deploy-website:
    needs: [website-test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        vercel-args: '--prod'

  # Package Extension
  package-extension:
    needs: [extension-test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: extension/package-lock.json
    
    - name: Install dependencies
      run: |
        cd extension
        npm ci
    
    - name: Install vsce
      run: npm install -g vsce
    
    - name: Package extension
      run: |
        cd extension
        vsce package
    
    - name: Upload extension artifact
      uses: actions/upload-artifact@v4
      with:
        name: extension-package
        path: extension/*.vsix
